### ISSUE TITLE
Python 3.10 removes *loop* parameter from Event()

### ISSUE THREAD

**Issue by martinnester** [TeskaLabs/asab#266]
When running the [Getting started code](https://asab.readthedocs.io/en/latest/get-started.html) from the docs using Python 3.10.4 the following error occurred.

```bash
asab-test % python3 main.py
Traceback (most recent call last):
  File "/Users/martinnester/Documents/code/asab-test/main.py", line 9, in <module>
    app = MyApplication()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/asab/abc/singleton.py", line 14, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/asab/application.py", line 121, in __init__
    self._stop_event = asyncio.Event(loop=self.Loop)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/locks.py", line 168, in __init__
    super().__init__(loop=loop)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
asab-test % 
```

**Comment by ateska** [comment]
Hi,

thanks for reporting.
This is already solved in upcoming release: https://github.com/TeskaLabs/asab/milestone/2 (hence in the current master branch).

Specifically it was resolved in this PR: https://github.com/TeskaLabs/asab/issues/185
