### ISSUE TITLE
Git Provider fix

### ISSUE THREAD

**Issue by eliska-n** [TeskaLabs/asab#295]
https://github.com/TeskaLabs/asab/blob/53d4c39444006fcc6698878b39f5c2619c4173bb/asab/library/providers/git.py#L99

```
25-Aug-2022 11:35:55.840196 ERROR asab.task Error '[Errno 17] File exists: '/tmp/asab.library.git/20d4453ac295766a4f1bdce26156dce6b6603f658c223b6c509e862ab35647eb'' during task:
Traceback (most recent call last):
  File "/home/eliska/teskalabs/asab/asab/task.py", line 100, in main
    await task
  File "/home/eliska/teskalabs/asab/asab/library/providers/git.py", line 106, in intialize_git_repo
    await self.ProactorService.execute(init_task)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/eliska/teskalabs/asab/asab/library/providers/git.py", line 99, in init_task
    os.makedirs(self.RepoPath, mode=0o700)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/asab.library.git/20d4453ac295766a4f1bdce26156dce6b6603f658c223b6c509e862ab35647eb'
```

**Comment by ateska** [comment]
`try: ... except FileExistsError: pass` is a usual construct here.
