### ISSUE TITLE
asab.library in python 3.11

### ISSUE THREAD

**Issue by eliska-n** [TeskaLabs/asab#405]
```
Traceback (most recent call last):
  File "/app/lmio-depositor/lmiodepositor/app.py", line 96, in reload_pipelines
    schema = await self.Library.read(self.Schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asab/library/service.py", line 192, in read
    itemio = await library.read(path)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asab/library/providers/zookeeper.py", line 227, in read
    node_data = await self.Zookeeper.get_data(node_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asab/zookeeper/wrapper.py", line 64, in get_data
    data, stat = await self.ProactorService.execute(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kazoo/client.py", line 1165, in get
    return self.get_async(path, watch=watch).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kazoo/handlers/utils.py", line 80, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed
```

according to @PremyslCerny, this happens specifically with python 3.11 in the very beginning of runtime - when first files are being read

**Comment by ateska** [comment]
This basically means that the ` self.Library.read(...)` is called before the connection to Zookeeper is established.
One needs to wait for "library ready" event. @PremyslCerny

**Comment by ateska** [comment]
Also, there should be a check that the library is actually ready, so that the error message is friendlier.
