### ISSUE TITLE
InfluxDB errors when recording metrics should not bring down the application

### ISSUE THREAD

**Issue by timthelion** [TeskaLabs/asab#426]
I'm seeing errors like:

```
--- Logging error ---

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/asab/metrics/influxdb.py", line 128, in _worker_upload

    conn.request("POST", self.WriteRequest, rb, self.Headers)

  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output

    self.send(msg)

  File "/usr/local/lib/python3.7/http/client.py", line 972, in send

    self.connect()

  File "/usr/local/lib/python3.7/http/client.py", line 944, in connect

    (self.host,self.port), self.timeout, self.source_address)

  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection

    raise err

  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection

    sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
```

This is causing a bitswan pump to stop. This kind of error should be a soft warning at most... Not cause disruptions to the application.

**Comment by ateska** [comment]
https://github.com/TeskaLabs/asab/blob/cfdd5113524d35b2deef1d4e8ab2796e837d4d1b/asab/metrics/influxdb.py#LL121C6-L121C20

**Comment by timthelion** [comment]
OK, thanks. Looks like it's time for an upgrade.

**Comment by ateska** [comment]
Also, can you provide the whole error log ...

```
		try:
			conn.request("POST", self.WriteRequest, rb, self.Headers)
		except ConnectionRefusedError:
			L.error("Failed to connect to InfluxDB at {}".format(self.BaseURL))
			return
```

The actual code handles the very exception and logs the error.
Basically exactly, what you are reporting.
It is there for ~1 year.

https://github.com/TeskaLabs/asab/blob/cfdd5113524d35b2deef1d4e8ab2796e837d4d1b/asab/metrics/influxdb.py#LL121C6-L121C20
