### ISSUE TITLE
Bug: Library - Filesystem Provider - subscribe

### ISSUE THREAD

**Issue by eliska-n** [TeskaLabs/asab#455]
I found that subscribing to the library in the filesystem provider is broken and it is because of this MR: https://github.com/TeskaLabs/asab/pull/407

Let's sum up asab.library functionality and discuss testing suits - manual or unit tests. It is becoming more and more important.

```
13-Jul-2023 14:00:35.948043 ERROR root Task exception was never retrieved
{'future': <Task finished name='Task-7' coro=<MyApplication.on_library_ready() done, defined at /home/eliska/teskalabs/playground/asab_library/asab-library-git-example.py:38> exception=TypeError("FileSystemLibraryProvider._list() missing 1 required positional argument: 'index'")>}
Traceback (most recent call last):
  File "/home/eliska/teskalabs/playground/asab_library/asab-library-git-example.py", line 46, in on_library_ready
    await self.LibraryService.subscribe("/")
  File "/home/eliska/teskalabs/asab/asab/library/service.py", line 383, in subscribe
    await provider.subscribe(path)
  File "/home/eliska/teskalabs/asab/asab/library/providers/filesystem.py", line 176, in subscribe
    self._subscribe_recursive(path, path)
  File "/home/eliska/teskalabs/asab/asab/library/providers/filesystem.py", line 188, in _subscribe_recursive
    items = self._list(path_to_be_listed)
TypeError: FileSystemLibraryProvider._list() missing 1 required positional argument: 'index'
```

_Originally posted by @eliska-n in https://github.com/TeskaLabs/asab/issues/448#issuecomment-1634136365_

**Comment by ateska** [comment]
https://github.com/TeskaLabs/asab/pull/448 ... this one has to be merged to address this issue.

**Comment by eliska-n** [comment]
sure. I didn't realize it solves this issue.
